<a href="https://colab.research.google.com/github/MuskanSingh400/Python_Basics/blob/main/Python_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world")

hello world


In [ ]:
print(1+2)

3


In [ ]:
x="symbi"
print(x)

symbi


In [ ]:
my_variable=10
#x="hello"
#age_1=25
#this_is_a_long_variable_name=True

In [ ]:
1_age=30
my-variable="error"

SyntaxError: invalid decimal literal (ipython-input-9-852959716.py, line 1)

In [ ]:
width=10
height=4
area=width*height
print(area)

40


In [ ]:
x,y,z="economics","management","computer science" #topic: assign multiple value
print(x,z)
print(y)
print(z)

economics computer science
management
computer science


In [ ]:
fruits="mango","apple","grapes" #topic:unpack a collection
x,y,z=fruits
print(z,y,z)

grapes apple grapes


In [ ]:
x=10                                # f string topic
y="hello"
print(f"The value of x is :{x}")
print(f"The value of y is:{y}")

The value of x is :10
The value of y is:hello


In [ ]:
p=4
q=6
result=p*q
print("the result of multiplication",result)

the result of multiplication 24


In [ ]:
my_variable=10
x="hello"
age_1=25
a=True
print(a)

True


In [ ]:
#numric types:
x=5 #int
y=3.14 #float
z=2+3  #complex
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'float'>
<class 'int'>


In [ ]:
# sequence types
s="hello"  #strg
l=[1,2,3]  #list
t=(4,5,6)  #tuple
print(type(s))
print(type(l))
print(type(t))



<class 'str'>
<class 'list'>
<class 'tuple'>


SyntaxError: unterminated string literal (detected at line 2) (ipython-input-27-3635859471.py, line 2)

In [ ]:
# converting data type
# 1. **int():** Convert a value to an integer data type.
x=3.14
y=int(x)
print(y)

x = int(3.14)  # x will be 3

# 2. **float():** Convert a value to a floating-point data type.

a=5 # int
y = float(a)  #int is converted to float
print(y)

# 3. **str():** Convert a value to a string data type.
y = 123 #int

z = str(y)  # z will be "123"
print(y)

# 4. **bool():** Convert a value to a boolean data type.

a = bool(0)  # a will be False
print(a)

# 5. **list():** Convert a sequence (e.g., tuple, string) to a list.

tuple1 = (1, 2, 3)
list1 = list(tuple1)  # list1 will be [1, 2, 3]
print(list1)

3
5.0
123
False
[1, 2, 3]


In [ ]:
#if and else condition
x=4
if x >5:
  print("x is greater than 5")
else:
  print("x is not greater than 5")

x is not greater than 5


In [ ]:
x=1
if x>10:
 print("x is greater than 10")
elif x == 10:
  print("x is equal to 10")
else:
  print("x is less than 10")

x is less than 10


In [ ]:
x=5
if x<5:
 print("x is less than 5")
elif x==5:
  print("x is equal to 5")
else:
  print("x is greater than 5")

x is equal to 5


In [ ]:
# Define two variables
a = 10
b = 20

Equals: a == b
if a == b:
    print("a is equal to b")
else:
    print("a is not equal to b")

# # Not Equals: a != b
if a != b:
    print("a is not equal to b")
else:
    print("a is equal to b")

# Less than: a < b. a=10 and b= 20
if a < b:
    print("a is less than b")
else:
    print("a is not less than b")

# Less than or equal to: a <= b
if a <= b:
    print("a is less than or equal to b")
else:
    print("a is greater than b")

# # Greater than: a > b
if a > b:
    print("a is greater than b")
else:
    print("a is not greater than b")

# # Greater than or equal to: a >= b
if a >= b:
    print("a is greater than or equal to b")
else:
    print("a is less than b")

a is not equal to b
a is not equal to b
a is less than b
a is less than or equal to b
a is not greater than b
a is less than b


In [ ]:
# while loop
x=0
while x < 5:
  print("count is:",x)
  x=x+1

count is: 0
count is: 1
count is: 2
count is: 3
count is: 4


In [ ]:
# for loop
numbers = [1,2,3,4,5,6]
print(numbers)
# print("break")
for x in numbers:
  print(x)


[1, 2, 3, 4, 5, 6]
1
2
3
4
5
6


In [ ]:

for x in range(1,10,2):             #start,end,difference
  print(x)

1
3
5
7
9


In [ ]:
 for x in "banana":   #for printing in the same line
  print(x,end='')

banana

In [ ]:
for x in "banana":  #for printing in different new line
  print(x)

b
a
n
a
n
a


In [2]:
#numpy
import numpy as np
a=np.array([1,2,3])
print(a*2)

[2 4 6]


In [11]:

# Python list vs NumPy speed test
import time
a = list(range(1000000)) #list
b = np.array(a) #numpy
start = time.time()
a2 = [x * 2 for x in a]
print("Python list time:", time.time() - start)
start = time.time()
b2 = b * 2
print("NumPy array time:", time.time() - start)

TypeError: 'list' object is not callable

In [15]:
import numpy as np
import builtins
builtins.print(np.__version__)

2.0.2


In [19]:
import numpy as np
import builtins
a = np.array([1, 2, 3], dtype=np.float32)
builtins.print(a.dtype)  # float32
# You can use dtype to save memory or improve performance.

float32


In [21]:
import numpy as np
import builtins
arr = np.array([[1, 2, 3], [4, 5, 6]])
builtins.print(arr.shape)     # (2, 3)
builtins.print(arr.ndim)      # 2
builtins.print(arr.size)      # 6
builtins.print(arr.itemsize)  # 8 (for int64)
builtins.print(arr.nbytes)    # 48

(2, 3)
2
6
8
48


In [24]:
import numpy as np
import builtins
# types of array
#1d
a=np.array([10,20,30,40])
builtins.print(a[3])
builtins.print(a[1:4])

40
[20 30 40]


In [26]:
#2d
b=np.array([[1,2,3],[4,5,6]])
builtins.print(b[0,1])
builtins.print(b[:,1])
builtins.print(b[1])

2
[2 5]
[4 5 6]


In [27]:
a = np.array([10, 20, 30, 40])
builtins.print(a[[0, 2]])  # [10 30]

# You can even reorder:

builtins.print(a[[3, 1, 0]])  # [40 20 10]

[10 30]
[40 20 10]


In [29]:
a = np.array([1, 2, 3, 4, 5])
mask = a > 3
builtins.print(mask)        # [False False False True True]
builtins.print(a[mask])     # [4 5]
# Or in one line:
builtins.print(a[a > 3])    # [4 5]

[False False False  True  True]
[4 5]
[4 5]


In [31]:
import numpy as np
import builtins
a=np.array([[1,2],[3,4]])
b=np.array([10,20])
builtins.print(a+b)

[[11 22]
 [13 24]]


In [32]:
a = np.array([[1, 2], [3, 4]]) # broadcasting error
b = np.array([10, 20, 30])
# This will raise an error because shapes don't align
builtins.print(a + b)

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [33]:
import numpy as np
import builtins
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
builtins.print(a + b)  # [11 22 33]
builtins.print(b - a)  # [9 18 27]
builtins.print(a * b)  # [10 40 90]
builtins.print(b / a)  # [10. 10. 10.]
# Arrays must have the same shape or be broadcast-compatible.

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [34]:
a=np.array([1,2,3])
a+=10  #same as a = a+10
builtins.print(a)

[11 12 13]


In [35]:
#comparison operaters
a=np.array([1,2,3])
b=np.array([2,2,2])
builtins.print(a>b)
builtins.print(a==b)
builtins.print(a!=b)

[False False  True]
[False  True False]
[ True False  True]


In [37]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
builtins.print(a + b)  # [11 22 33]
builtins.print(b - a)  # [9 18 27]
builtins.print(a * b)  # [10 40 90]
builtins.print(b / a)  # [10. 10. 10.]
# Arrays must have the same shape or be broadcast-compatible.

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [38]:
a = np.array([1, 2, 3, 4])
builtins.print(np.sum(a))   # 10
builtins.print(np.mean(a))  # 2.5
builtins.print(np.min(a))   # 1
builtins.print(np.std(a))   # 1.118...

10
2.5
1
1.118033988749895


In [39]:
# Mini Practice
a = np.array([[10, 20], [30, 40]])
# 1. Square root
builtins.print(np.sqrt(a))
# 2. Row-wise mean
builtins.print(np.mean(a, axis=1))
# 3. Which values are > 25?
builtins.print(a > 25)

[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]
[15. 35.]
[[False False]
 [ True  True]]


In [ ]:
#reshape array
import numpy as np
a = np.array([1,2,3,4,5])


In [41]:
#transposing and swapping
a = np.array([[1, 2], [3, 4]])
builtins.print(a.transpose())

[[1 3]
 [2 4]]


In [42]:
#stacking arrays
a=np.array([1,2,3])
b=np.array([4,5,6])
builtins.print(np.vstack((a,b)))  #vertical stacking

[[1 2 3]
 [4 5 6]]


In [44]:
builtins.print(np.hstack((a,b)))  #horizontal stacking

[1 2 3 4 5 6]


In [46]:
#flitering ,sorting and searching
#condition selection
a=np.array([10,20,30,40])
result=np.where(a>25,1,0)
builtins.print(result)



[0 0 1 1]
